version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:2.0
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "dotnet restore ./MvcTest.sln && dotnet publish ./MvcTest.sln -c Release -o ./obj/Docker/publish && ls"
